name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install backend dependencies
      run: |
        cd backend
        npm install
        cd ..

    - name: Install frontend dependencies
      run: |
        cd frontend/medi-records
        npm install

    - name: Run frontend tests
      run: |
        cd frontend/medi-records
        npm test

    - name: Build the site
      run: |
        cd frontend/medi-records
        npm run build
